# Generated by Django 5.1.1 on 2024-11-30 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.IntegerField(default=0)),
                ('tentativas', models.IntegerField(default=0)),
                ('tempo_gasto', models.DurationField(blank=True, null=True)),
                ('data_jogo', models.DateTimeField(auto_now_add=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='task.jogador')),
            ],
        ),
    ]
